# Shared definition block
shared:
  # Source: https://hub.docker.com/r/library/buildpack-deps/
  image: buildpack-deps
  
# Job definition block, "main" is a default job that all pipelines have
jobs:
  main:
    requires: [ ~pr, ~commit ]
    steps:
      - export: export GREETING="Hello, there, Russ!"
      - hello: echo $GREETING
