# Job definition block
# "main" is a default job that all pipelines have
jobs:
  main:
    # Steps definition block.
    steps:
      - export: export GREETING="Hello, there, Russ!"
      - hello: echo $GREETING
